myapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('requestmovie/', views.requestmovie, name='requestmovie'),
    path('createmovie/', views.createmovie, name='createmovie'),
    path('createlist/', views.createlist, name='createlist'),
    path('requests/', views.requests, name='requests'),
    path('profile/', views.userprofile, name='userprofile'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('search/', views.search_view, name='search'),
    path('donate/', views.donate, name='donate'),
    path('login/', views.login_view, name='login'),
    re_path(r'addtoplaylist/(?P<playlist_slug>[\w-]+)/(?P<movie_slug>[\w-]+)/$',
            views.addtoplaylist, name='addtoplaylist'),
    re_path(r'removefromplaylist/(?P<playlist_slug>[\w-]+)/(?P<movie_slug>[\w-]+)/$',
            views.removefromplaylist, name='removefromplaylist'),
    re_path(r'^movie/(?P<slug>[\w-]+)/$',
            views.moviedetails, name='moviedetails'),
    re_path(r'^playlist/(?P<slug>[\w-]+)/$',
            views.playlistdetails, name='playlistdetails'),
    path('', views.home, name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'project'

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]

myapp/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import date
import re

LANGUAGE_CHOICES = (
    ('ar-AE', 'Arabic (United Arab Emirates)'),
    ('bn-BD', 'Bengali (Bangladesh)'),
    ('bn-IN', 'Bengali (India)'),
    ('zh-CN', 'Chinese (China)'),
    ('en-US', 'English (United States)'),
    ('fr-FR', 'French (France)'),
    ('de-DE', 'German (Germany)'),
    ('hi', 'Hindi (India)'),
    ('id', 'Indonesian (Indonesia)'),
    ('ja', 'Japanese (Japan)'),
    ('ko-KR', 'Korean (South Korea)'),
    ('pt-PT', 'Portuguese (Portugal)'),
    ('es-ES', 'Spanish (Spain)'),
    ('ta-IN', 'Tamil (India)'),
    ('th', 'Thai (Thailand)'),
)


class Movie(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=128,
                             blank=False,
                             verbose_name='Title')
    releasedate = models.DateField(blank=False,
                                   verbose_name='Release date')
    slug = models.SlugField(blank=True,
                            verbose_name='slug')
    language = models.CharField(max_length=32,
                                default='en-US',
                                choices=LANGUAGE_CHOICES,
                                verbose_name='Language')
    m_type = models.CharField(max_length=32,
                              default='Movie',
                              verbose_name='Type')
    description = models.TextField(max_length=512,
                                   default='N/A',
                                   verbose_name='Description')

    def __str__(self):
        year = self.releasedate.year
        return f'{year} | {self.title}'

    def save(self, *args, **kwargs):
        title = self.title
        releasedate = self.releasedate

        slug_t = re.sub(r'&', '-and-', title.lower())
        slug_t = re.sub(r'[\s\W-]+', '-', slug_t)
        self.slug = f'{releasedate.year}-{slug_t}'

        super(Movie, self).save(*args, **kwargs)

    def is_released(self):
        now = date.today()

        if self.releasedate < now:
            return True

        return False


class Playlist(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=32,
                             verbose_name='Title',)
    slug = models.SlugField(default='',
                            verbose_name='Slug',)
    p_type = models.CharField(max_length=32,
                              default='Playlist',
                              verbose_name='Type',)
    movies = models.ManyToManyField(Movie,
                                    blank=True,
                                    verbose_name='Movies',)
    createdby = models.ForeignKey(User,
                                  on_delete=models.CASCADE,
                                  verbose_name='Created by',)
    description = models.TextField(blank=True,
                                   default='N/A',
                                   max_length=512,
                                   verbose_name='Description')

    def __str__(self):
        return f'User: {self.createdby.username} | Title: {self.title}'

    def save(self, *args, **kwargs):
        user = self.createdby
        title = self.title
        slug_t = re.sub(r'&', '-and-', title)
        slug_t = re.sub(r'[\s\W-]+', '', slug_t)
        self.slug = f'{user.username}-{slug_t}'

        super(Playlist, self).save(*args, **kwargs)


class UserProfile(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_paid = models.BooleanField(default=False,
                                  help_text='Designates weather this user is premium',
                                  verbose_name='Premium')

    def __str__(self):
        return self.user.username


class RequestMovie(models.Model):
    id = models.BigAutoField(primary_key=True)
    movietitle = models.CharField(max_length=128,
                                  blank=False,
                                  verbose_name='Movie title')
    releasedate = models.DateField(blank=False,
                                   help_text='mm / dd / yyyy',
                                   verbose_name='Release date')
    language = models.CharField(max_length=32,
                                default='en-US',
                                choices=LANGUAGE_CHOICES,
                                verbose_name='Language')
    requestedby = models.ForeignKey(User,
                                    on_delete=models.CASCADE,
                                    blank=True,
                                    null=True,
                                    related_name='requested',
                                    verbose_name='Requested by')
    acceptedby = models.ForeignKey(User,
                                   on_delete=models.CASCADE,
                                   blank=True,
                                   null=True,
                                   related_name='accepted',
                                   verbose_name='Accepted by')
    accepted = models.BooleanField(default=False,
                                   help_text='Designates weather this request is acccepted.',
                                   verbose_name='Accepted')
    rejected = models.BooleanField(default=False,
                                   help_text='Designates weather this request is rejected.',
                                   verbose_name='Rejected')

    def __str__(self) -> str:
        return f'{self.id} | {self.requestedby}'

project/views.py
from django.shortcuts import render


def homepage(request):
	return render(request, 'homepage.html')

project/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'images/film_movie.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'responsive.css' %}">
    <link rel="stylesheet" href="{% static 'nav_sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'jquery-ui.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#id_releasedate").datepicker();
        });
    </script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <!-- Container -->
    <div id="container">
        <!-- Header -->
        <div id="header">
            <div id="branding">
                <h1 id="site-name"><a href="{% url 'myapp:home' %}"><img
                            src="{% static 'images/film-frames-apple.png' %}" height=40px width=40px>
                        Movie Watchlist</a></h1>
            </div>

            <div id="user-tools">
                {% if user.is_authenticated %}
                <div class="inline-flex">Welcome,&nbsp<a href="{% url 'myapp:userprofile' %}"><strong>{{ user.username }}</strong></a>
                    <form id="logout-link" action="{% url 'myapp:logout' %}" method="post">
                        {% csrf_token %}
                        &nbsp<button type="submit">Logout</button>
                    </form>
                </div>
                <div>
                    <!-- if user is admin/staff, can add new movie -->
                    {% if user.is_staff %}
                    <a href="{% url 'myapp:createmovie' %}">Add Movie</a>
                    {% endif %}

                    <!-- if user is premium, can create new playlist -->
                    <!-- if user is premium, can request a movie -->
                    {% if user.userprofile.is_paid %}
                    &nbsp|&nbsp<a href="{% url 'myapp:createlist' %}">New Playlist</a>
                    {% endif %}
                    {% if user.userprofile.is_paid and not user.is_stuff %}
                    &nbsp|&nbsp<a href="{% url 'myapp:requests' %}">Check Requests</a>
                    &nbsp|&nbsp<a href="{% url 'myapp:requestmovie' %}">Request a Movie</a>
                    {% endif %}
                </div>
                {% else %}
                <a href="{% url 'myapp:login' %}">Login</a>
                &nbsp|&nbsp<a href="{% url 'myapp:signup' %}">Signup</a>
                {% endif %}
            </div>

        </div>
        <!-- END Header -->
        <!-- Navbar -->
        <div class="breadcrumbs">
            <form action="{% url 'myapp:search' %}" method="POST">
                {% csrf_token %}
                <input type="search" placeholder="Search" name="searched">
                <button type="submit">Search</button>
            </form>
        </div>
        <!-- END Navbar -->
        <div class="main shifted" id="main">
            <!-- Content -->
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!-- END Container -->
</body>

</html>