myapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('requestmovie/', views.requestmovie, name='requestmovie'),
    path('createmovie/', views.createmovie, name='createmovie'),
    path('createlist/', views.createlist, name='createlist'),
    path('requests/', views.requests, name='requests'),
    path('profile/', views.userprofile, name='userprofile'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('search/', views.search_view, name='search'),
    path('donate/', views.donate, name='donate'),
    path('login/', views.login_view, name='login'),
    re_path(r'addtoplaylist/(?P<playlist_slug>[\w-]+)/(?P<movie_slug>[\w-]+)/$',
            views.addtoplaylist, name='addtoplaylist'),
    re_path(r'removefromplaylist/(?P<playlist_slug>[\w-]+)/(?P<movie_slug>[\w-]+)/$',
            views.removefromplaylist, name='removefromplaylist'),
    re_path(r'^movie/(?P<slug>[\w-]+)/$',
            views.moviedetails, name='moviedetails'),
    re_path(r'^playlist/(?P<slug>[\w-]+)/$',
            views.playlistdetails, name='playlistdetails'),
    path('', views.home, name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'project'

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
]

myapp/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import date
import re

LANGUAGE_CHOICES = (
    ('ar-AE', 'Arabic (United Arab Emirates)'),
    ('bn-BD', 'Bengali (Bangladesh)'),
    ('bn-IN', 'Bengali (India)'),
    ('zh-CN', 'Chinese (China)'),
    ('en-US', 'English (United States)'),
    ('fr-FR', 'French (France)'),
    ('de-DE', 'German (Germany)'),
    ('hi', 'Hindi (India)'),
    ('id', 'Indonesian (Indonesia)'),
    ('ja', 'Japanese (Japan)'),
    ('ko-KR', 'Korean (South Korea)'),
    ('pt-PT', 'Portuguese (Portugal)'),
    ('es-ES', 'Spanish (Spain)'),
    ('ta-IN', 'Tamil (India)'),
    ('th', 'Thai (Thailand)'),
)


class Movie(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=128,
                             blank=False,
                             verbose_name='Title')
    releasedate = models.DateField(blank=False,
                                   verbose_name='Release date')
    slug = models.SlugField(blank=True,
                            verbose_name='slug')
    language = models.CharField(max_length=32,
                                default='en-US',
                                choices=LANGUAGE_CHOICES,
                                verbose_name='Language')
    m_type = models.CharField(max_length=32,
                              default='Movie',
                              verbose_name='Type')
    description = models.TextField(max_length=512,
                                   default='N/A',
                                   verbose_name='Description')

    def __str__(self):
        year = self.releasedate.year
        return f'{year} | {self.title}'

    def save(self, *args, **kwargs):
        title = self.title
        releasedate = self.releasedate

        slug_t = re.sub(r'&', '-and-', title.lower())
        slug_t = re.sub(r'[\s\W-]+', '-', slug_t)
        self.slug = f'{releasedate.year}-{slug_t}'

        super(Movie, self).save(*args, **kwargs)

    def is_released(self):
        now = date.today()

        if self.releasedate < now:
            return True

        return False


class Playlist(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=32,
                             verbose_name='Title',)
    slug = models.SlugField(default='',
                            verbose_name='Slug',)
    p_type = models.CharField(max_length=32,
                              default='Playlist',
                              verbose_name='Type',)
    movies = models.ManyToManyField(Movie,
                                    blank=True,
                                    verbose_name='Movies',)
    createdby = models.ForeignKey(User,
                                  on_delete=models.CASCADE,
                                  verbose_name='Created by',)
    description = models.TextField(blank=True,
                                   default='N/A',
                                   max_length=512,
                                   verbose_name='Description')

    def __str__(self):
        return f'User: {self.createdby.username} | Title: {self.title}'

    def save(self, *args, **kwargs):
        user = self.createdby
        title = self.title
        slug_t = re.sub(r'&', '-and-', title)
        slug_t = re.sub(r'[\s\W-]+', '', slug_t)
        self.slug = f'{user.username}-{slug_t}'

        super(Playlist, self).save(*args, **kwargs)


class UserProfile(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_paid = models.BooleanField(default=False,
                                  help_text='Designates weather this user is premium',
                                  verbose_name='Premium')

    def __str__(self):
        return self.user.username


class RequestMovie(models.Model):
    id = models.BigAutoField(primary_key=True)
    movietitle = models.CharField(max_length=128,
                                  blank=False,
                                  verbose_name='Movie title')
    releasedate = models.DateField(blank=False,
                                   help_text='mm / dd / yyyy',
                                   verbose_name='Release date')
    language = models.CharField(max_length=32,
                                default='en-US',
                                choices=LANGUAGE_CHOICES,
                                verbose_name='Language')
    requestedby = models.ForeignKey(User,
                                    on_delete=models.CASCADE,
                                    blank=True,
                                    null=True,
                                    related_name='requested',
                                    verbose_name='Requested by')
    acceptedby = models.ForeignKey(User,
                                   on_delete=models.CASCADE,
                                   blank=True,
                                   null=True,
                                   related_name='accepted',
                                   verbose_name='Accepted by')
    accepted = models.BooleanField(default=False,
                                   help_text='Designates weather this request is acccepted.',
                                   verbose_name='Accepted')
    rejected = models.BooleanField(default=False,
                                   help_text='Designates weather this request is rejected.',
                                   verbose_name='Rejected')

    def __str__(self) -> str:
        return f'{self.id} | {self.requestedby}'

myapp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Movie, Playlist, RequestMovie, UserProfile


class CreateMovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = ('title',
                  'releasedate',
                  'slug',
                  'language',
                  'description',)


class CreatePlaylistForm(ModelForm):
    class Meta:
        model = Playlist
        fields = ('title',
                #   'slug',
                  'description',)


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=32,
                                 required=False,
                                 help_text='Optional.')
    last_name = forms.CharField(max_length=32,
                                required=False,
                                help_text='Optional.')
    email = forms.EmailField(max_length=256,
                             help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('first_name',
                  'last_name',
                  'username',
                  'email',
                  'password1',
                  'password2',)


class RequestMovieForm(ModelForm):
    class Meta:
        model = RequestMovie
        fields = ('movietitle',
                  'releasedate',
                  'language',)


class PaymentForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ('is_paid',)

myapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .models import Playlist, Movie, UserProfile, RequestMovie
from . import forms
import re


# Custom decorators
def anonymous_required(function=None, redirect_url=None):
    """
        Decorator for views that checks that any user is not logged in, redirecting
        to the log-in page if necessary.
    """
    actual_decorator = user_passes_test(
        lambda u: u.is_anonymous,
        login_url=redirect_url,
    )
    if function:
        return actual_decorator(function)
    return actual_decorator


# def free_user_required(function=None, redirect_url=None):
#     """
#         Decorator for views that checks that any user is not logged in, redirecting
#         to the log-in page if necessary.
#     """
#     actual_decorator = user_passes_test(
#         lambda u: not u.userprofile.is_paid,
#         login_url=redirect_url,
#     )
#     if function:
#         return actual_decorator(function)
#     return actual_decorator


# Main views
def home(request):
    movies = Movie.objects.all().order_by('-releasedate__year', 'title')
    playlists = Playlist.objects.all().order_by('createdby', 'title')
    context = {
        'movies': movies,
        'playlists': playlists,
    }
    return render(request, 'myapp/collection.html', context)


def moviedetails(request, slug):
    movie = Movie.objects.all().get(slug=slug)
    playlists = Playlist.objects.filter(createdby=request.user.id)
    context = {
        'movie': movie,
        'playlists': playlists,
    }
    return render(request, 'myapp/moviedetails.html', context)


@anonymous_required(redirect_url='myapp:home')
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('myapp:home')
    else:
        form = AuthenticationForm()
    return render(request, 'myapp/login.html', {'form': form})


@anonymous_required
def signup_view(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            userprofile = UserProfile(user=user)
            userprofile.save()
            #########################################################
            liked = Playlist(title='Liked', createdby=user,
                             slug=f'{user}-liked',
                             description='All the liked movies.')
            watched = Playlist(title='Watched', createdby=user,
                               slug=f'{user}-watched',
                               description='All the watched movies.')
            liked.save()
            watched.save()
            #########################################################
            login(request, user)
            return redirect('myapp:home')
    else:
        form = forms.SignUpForm()
    return render(request, 'myapp/signup.html', {'form': form})


def search_view(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        movies = Movie.objects.filter(title__contains=searched).order_by(
            '-releasedate__year', 'title')
        try:
            movies_date = Movie.objects.filter(
                releasedate__year=searched).order_by('-releasedate__year', 'title')
        except:
            movies_date = []

        context = {'searched': searched,
                   'movies': movies,
                   'movies_date': movies_date}
        return render(request, 'myapp/search.html', context=context)
    else:
        return render(request, 'myapp/search.html')


# FREE Users
@login_required(login_url='myapp:login')
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('myapp:home')


@login_required(login_url='myapp:login')
def userprofile(request):
    playlists = Playlist.objects.filter(createdby=request.user.id)
    context = {
        'playlists': playlists,
    }
    return render(request, 'myapp/userprofile.html', context)


@login_required(login_url='myapp:login')
def playlistdetails(request, slug):
    playlist = Playlist.objects.all().get(slug=slug)
    all_movies = playlist.movies.all()
    context = {
        'playlist': playlist,
        'movies': all_movies,
    }
    return render(request, 'myapp/playlistdetails.html', context)


@login_required(login_url='myapp:login')
def donate(request):
    if request.method == 'POST':
        payment = request.POST.get('payment')
        if payment == 'paid':
            userprofile = request.user.userprofile
            userprofile.is_paid = True
            userprofile.save()

        if 'next' in request.POST:
            return redirect(request.POST.get('next'))
        else:
            return redirect('myapp:userprofile')
    return render(request, 'myapp/donate.html')


@login_required(login_url='myapp:login')
def addtoplaylist(request, playlist_slug, movie_slug):
    if request.method == 'POST':
        playlist = Playlist.objects.all().get(slug=playlist_slug)
        movie = Movie.objects.all().get(slug=movie_slug)
        playlist.movies.add(movie)
        return redirect('myapp:moviedetails', slug=movie_slug)


@login_required(login_url='myapp:login')
def removefromplaylist(request, playlist_slug, movie_slug):
    if request.method == 'POST':
        playlist = Playlist.objects.all().get(slug=playlist_slug)
        movie = Movie.objects.all().get(slug=movie_slug)
        playlist.movies.remove(movie)
        return redirect('myapp:playlistdetails', slug=playlist_slug)


# PREMIUM Users
@login_required(login_url='myapp:login')
def createlist(request):
    if request.method == 'POST':
        form = forms.CreatePlaylistForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.createdby = request.user
            instance.save()
            return redirect('myapp:home')
    else:
        form = forms.CreatePlaylistForm()

    return render(request, 'myapp/createlist.html', {'form': form})


@login_required(login_url='myapp:login')
def requests(request):
    if request.user.is_staff:
        requests = RequestMovie.objects.all().order_by('id')
        context = {'requests': requests, }

        if request.method == 'POST':
            action = request.POST.get('action')
            req_id = request.POST.get('request_id')
            req = RequestMovie.objects.filter(id=req_id)[0]

            if action == '✔️':
                title = req.movietitle
                date = req.releasedate
                f_title = re.sub(r'[\s\W-]+', '-',
                                 re.sub(r'&', '-and-', title.strip().lower()))
                slug = f'{str(date)[:4]}-{f_title}'
                lang = req.language
                newmovie = Movie(title=title,
                                 slug=slug,
                                 releasedate=date,
                                 language=lang)
                newmovie.save()
                req.accepted = True
                req.acceptedby = request.user
                req.save()

            elif action == '❌':
                req.delete()

            return redirect('myapp:requests')

        return render(request, 'myapp/requests.html', context=context)

    elif request.user.userprofile.is_paid:
        requests = RequestMovie.objects.filter(
            requestedby=request.user).order_by('id')
        context = {'requests': requests, }

        return render(request, 'myapp/requests.html', context=context)


@login_required(login_url='myapp:login')
def requestmovie(request):
    if request.method == 'POST':
        form = forms.RequestMovieForm(request.POST)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.requestedby = request.user
            instance.save()
            return redirect('myapp:requestmovie')

    else:
        form = forms.RequestMovieForm()

    return render(request, 'myapp/requestmovie.html', {'form': form})


# ADMIN Users
@login_required(login_url='myapp:login')
def createmovie(request):
    if request.method == 'POST':
        form = forms.CreateMovieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('myapp:createmovie')
    else:
        form = forms.CreateMovieForm()

    return render(request, 'myapp/createmovie.html', {'form': form})

myapp/templates/myapp/collection.html
{% extends 'base_layout.html' %}
{% load custom_filters %}

{% block title %} Movie collection {% endblock %}

{% block content %}
<div class="content" class="colM">
    <h1>Movie Collections</h1>

    <!-- Show only the movies released in the future -->
    <div id="container">
        <div id="inline-flex">
            <div>
                <h2>Realeased</h2>
                <div class="divScroll">
                    {% for movie in movies %}
                    {% if movie.is_released %}
                    <h4> {{movie.releasedate|date:'Y'}} | <a
                            href="{% url 'myapp:moviedetails' slug=movie.slug %}">{{movie.title}}</a>
                    </h4>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div>
                <h2>Coming soon</h2>
                <div class="divScroll">
                    {% for movie in movies %}
                    {% if not movie.is_released %}
                    <h4> {{movie.releasedate|date:'Y'}} ({{movie.releasedate|date:'M'}}) |
                        <a href="{% url 'myapp:moviedetails' slug=movie.slug %}">{{movie.title}}</a>
                    </h4>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

myapp/templates/myapp/createlist.html
{% extends 'base_layout.html' %}

{% block title %} Create playlist {% endblock %}

{% block content %}
<div id="content" class="colM">
    <h1>Create Playlist</h1>

    <div id="content-main">
        <form id="playlist_form" action="{% url 'myapp:createlist' %}" method="POST">
            {% csrf_token %}
            <!-- {{ form }} -->
            <div>
                <fieldset class="module aligned">
                    {% for field in form %}
                    <div class="form-row">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                        <small style="color: grey">{{ field.help_text }}</small>
                        {% endif %}
                        {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </fieldset>
                <input type="submit" value="Create">
            </div>
        </form>
    </div>
</div>
{% endblock %}

myapp/templates/myapp/createmovie.html
{% extends 'base_layout.html' %}

{% block title %} Create movie {% endblock %}

{% block content %}
<div id="content" class="colM">
    <h1>Create Movie</h1>

    <div id="content-main">
        <form id="movie_form" action="{% url 'myapp:createmovie' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- {{ form }} -->
            <div>
                <fieldset class="module aligned">
                    {% for field in form %}
                    <div class="form-row">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                        <small style="color: grey">{{ field.help_text }}</small>
                        {% endif %}
                        {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </fieldset>
                <input type="submit" value="Create" onclick="return alert('Movie created successfully.');">
            </div>
        </form>
    </div>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

myapp/templates/myapp/donate.html
{% extends 'base_layout.html' %}

{% block title %}Donate{% endblock %}

{% block content %}

    {% if user.userprofile.is_paid %}
        <p>Congratulations! You are a Premium user.</p>
        <p>Thank you for your donation.</p>
    {% else %}
        <div>
            <h1>Payment confirmation</h1>
            <form action="{% url 'myapp:donate' %}" id="site-form" method="post">
                {% csrf_token %}
                <!-- {{ form }} -->
                <input type="hidden" name="payment" value="paid">
                <input type="submit" value="Confirm payment" onclick="return confirm('Donate at your own risk!\nPayment is not Refundable.');">
            </form>
        </div>
    {% endif %}

{% endblock %}

myapp/templates/myapp/moviedetails.html
{% extends 'base_layout.html' %}
{% load custom_filters %}

{% block title %}Movie details{% endblock %}

{% block content %}
<div id="content" class="colM">
    <div id="container">
        <div id="inline-flex">
            <div class="info">

                <table>
                    <caption>🎬 {{ movie.title }}</caption>
                    <tbody>
                        <tr>
                            <th>Release Date:</th>
                            <td>{{ movie.releasedate }}</td>
                        </tr>
                        <tr>
                            <th>Language:</th>
                            <td>{{ movie|display_as:'language' }}</td>
                        </tr>
                        <tr>
                            <th>Description:</th>
                            {% if movie.description == '' %}
                            <td>N/A</td>
                            {% else %}
                            <td>{{ movie.description }}</td>
                            {% endif %}
                        </tr>
                    </tbody>
                </table>
            </div>
            {% if user.is_authenticated %}
            <div class="add-to-playlist">
                <h1>Add to playlists: </h1>
                <div id="playlists">
                    {% for playlist in playlists %}
                    <form id="addtoplaylist-link"
                        action="{% url 'myapp:addtoplaylist' playlist_slug=playlist.slug movie_slug=movie.slug %}"
                        method="post">
                        {% csrf_token %}
                        <input type="submit" value="{{ playlist.title }}"
                            onclick="return alert ('Movie has been added to {{ playlist.title }}')">
                    </form>&nbsp;
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock%}

myapp/templates/myapp/playlistdetails.html
{% extends 'base_layout.html' %}
{% load custom_filters %}

{% block title %}Playlist details{% endblock %}

<h5>⇒ TODO: let users add/remove movie to playlist.</h5>

{% block content %}
    <div id="container">
        <h1>{{ user.username }}'s <strong>{{ playlist.title }}</strong> Playlist</h1>
        {% if playlist.description != '' %}
            <p>{{ user.username }}'s {{ playlist.description }} Playlist</p>
        {% endif %}
        {% for movie in movies %}
            <div class="set">
                <form id="removefromplaylist-link"
                    action="{% url 'myapp:removefromplaylist' playlist_slug=playlist.slug movie_slug=movie.slug %}" 
                    method="post">
                    {% csrf_token %}
                    <!-- {{ form }} -->
                    <button type="submit" style="border:None; background:None;" name="remove">❌</button>&nbsp&nbsp
                </form>
                <h4>{{movie.releasedate|date:'Y'}} | <a href="{% url 'myapp:moviedetails' slug=movie.slug %}">{{movie.title}}</a></h4>
            </div>
        {% endfor %}
    </div>
{% endblock %}

myapp/templates/myapp/requestmovie.html
{% extends 'base_layout.html' %}

{% block title %} Make Request {% endblock %}

{% block content %}
    <div id="content" class="colM">
        <h1>Make Request</h1>

        <div id="content-main">
            <form id="requestmovie_form" action="{% url 'myapp:requestmovie' %}" method="POST">
                {% csrf_token %}
                <!-- {{ form }} -->
                <div>
                    <fieldset class="module aligned">
                        {% for field in form %}
                        <div class="form-row">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <small style="color: grey">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endfor %}
                    </fieldset>
                    <input type="submit" value="Request" onclick="return confirm('Press \'OK\' to confirm your request.')">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'images/film_movie.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'nav_sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <link rel="stylesheet" href="{% static 'responsive.css' %}">
    <script src="{% static 'nav_sidebar.js' %}"></script>
    <title>Signup | Movie Watchlist</title>
</head>

<body class="login">
    <!-- Container -->
    <div id="container">
        <!-- Header -->
        <div id="header">
            <div id="branding">
                <h1 id="site-name">
                    <a href="{% url 'myapp:home' %}"><img src="{% static 'images/film-frames-apple.png' %}" height=50px width=50px>&nbsp;Movie Watchlist</a>
                </h1>
            </div>
        </div>
        <!-- END Header -->
        <div class="main shifted">
            <div class="content">
                <!-- Content -->
                <div id="content" class="colM">
                    <div id="content-main">
                        <form action="{% url 'myapp:signup' %}" method="post" id="login-form">
                            {% csrf_token %}
                            <!-- {{ form }} -->
                            {% for field in form %}
                            <div class="form-row">
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.help_text %}
                                <small style="color: grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </div>
                            {% endfor %}

                            {% if request.GET.next %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                            {% endif %}
                            <div class="submit-row">
                                <input type="submit" value="Sign up">
                            </div>
                        </form>
                    </div>
                </div>
                <!-- END Content -->
                <div id="footer"></div>
            </div>
        </div>
    </div>
</body>

myapp/templates/myapp/userprofile.html
{% extends 'base_layout.html' %}
{% load custom_filters %}

{% block title %}{{ user.username }} | Profile{% endblock %}

{% block content %}
<div id="content" class="colM">
    <div id="container">
        <div id="inline-flex">
            <div class="info">
                <h1><strong>{{ user|display_as:'fullname'|upper }}'s PROFILE</strong></h1>
                <table>
                    <caption><strong>Details</strong></caption>
                    <tbody>
                        <tr>
                            <th>First name:</th>
                            <td>{{ user.first_name }}</td>
                        </tr>
                        <tr>
                            <th>Last name:</th>
                            <td>{{ user.last_name }}</td>
                        </tr>
                        <th>Username:</th>
                        <td>{{ user.username }}</td>
                        <tr>
                            <th>Email:</th>
                            <td>{{ user.email }}</td>
                        </tr>
                        <tr>
                            <th>Date joined:</th>
                            <td>{{ user.date_joined }}</td>
                        </tr>
                        <tr>
                            <th>Premium info:</th>
                            {% if user.userprofile.is_paid %}
                            <td>Premium user</td>
                            {% else %}
                            <td>Free user | <a href="{% url 'myapp:donate' %}">Buy premium</a> for only $0.99.</td>
                            {% endif %}
                        </tr>
                    </tbody>
                </table>
            </div>
            <div>
                <h1>Playlists</h1>
                <div id="playlists">
                    {% for playlist in playlists %}
                    <a href="{% url 'myapp:playlistdetails' slug=playlist.slug %}">{{ playlist.title }}</a>&nbsp;<br>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}